//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsriCo.ArcGISRuntime.Xamarin.Forms {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EsriCo.ArcGISRuntime.Xamarin.Forms.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acres.
        /// </summary>
        public static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Portal.
        /// </summary>
        public static string AddPortalButtonText {
            get {
                return ResourceManager.GetString("AddPortalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal Degrees.
        /// </summary>
        public static string DecimalDegrees {
            get {
                return ResourceManager.GetString("DecimalDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Degrees,Decimal Minutes.
        /// </summary>
        public static string DegreesDecimalMinutes {
            get {
                return ResourceManager.GetString("DegreesDecimalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Degrees,Minutes,Seconds.
        /// </summary>
        public static string DegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("DegreesMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant&apos; delete Replica Register Id:.
        /// </summary>
        public static string DeleteReplicaMessageCantDelete {
            get {
                return ResourceManager.GetString("DeleteReplicaMessageCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replica Register deleted Id: .
        /// </summary>
        public static string DeleteReplicaMessageDeleted {
            get {
                return ResourceManager.GetString("DeleteReplicaMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replica deleted.
        /// </summary>
        public static string DeleteReplicaMessageDone {
            get {
                return ResourceManager.GetString("DeleteReplicaMessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description: {0}.
        /// </summary>
        public static string DescriptionStringFormat {
            get {
                return ResourceManager.GetString("DescriptionStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        public static string DownloadReplicaOkMessageMap {
            get {
                return ResourceManager.GetString("DownloadReplicaOkMessageMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a saved.
        /// </summary>
        public static string DownloadReplicaOkMessageSaved {
            get {
                return ResourceManager.GetString("DownloadReplicaOkMessageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feet.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group: .
        /// </summary>
        public static string GroupLabelText {
            get {
                return ResourceManager.GetString("GroupLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectares.
        /// </summary>
        public static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Password:.
        /// </summary>
        public static string HidePasswordLabelText {
            get {
                return ResourceManager.GetString("HidePasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legend.
        /// </summary>
        public static string LegendPanelTitleText {
            get {
                return ResourceManager.GetString("LegendPanelTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Map.
        /// </summary>
        public static string LoadMapButtonText {
            get {
                return ResourceManager.GetString("LoadMapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LogInButtonText {
            get {
                return ResourceManager.GetString("LogInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LoginLabelText {
            get {
                return ResourceManager.GetString("LoginLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measurement.
        /// </summary>
        public static string MeasurementTitleText {
            get {
                return ResourceManager.GetString("MeasurementTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Update: {0:yyyy-MM-dd}.
        /// </summary>
        public static string ModifiedDateStringFormat {
            get {
                return ResourceManager.GetString("ModifiedDateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner: {0}.
        /// </summary>
        public static string OwnerStringFormat {
            get {
                return ResourceManager.GetString("OwnerStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        public static string PasswordLabelText {
            get {
                return ResourceManager.GetString("PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portals.
        /// </summary>
        public static string PortalsLabelText {
            get {
                return ResourceManager.GetString("PortalsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing....
        /// </summary>
        public static string ProcessingMessageLabelText {
            get {
                return ResourceManager.GetString("ProcessingMessageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square Feet.
        /// </summary>
        public static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square Kilometers.
        /// </summary>
        public static string SquareKilometers {
            get {
                return ResourceManager.GetString("SquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square Meters.
        /// </summary>
        public static string SquareMeters {
            get {
                return ResourceManager.GetString("SquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square Miles.
        /// </summary>
        public static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square Yards.
        /// </summary>
        public static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text:.
        /// </summary>
        public static string TextLabelText {
            get {
                return ResourceManager.GetString("TextLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title: {0}.
        /// </summary>
        public static string TitleStringFormat {
            get {
                return ResourceManager.GetString("TitleStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table of Contents.
        /// </summary>
        public static string TOCPanelTitleText {
            get {
                return ResourceManager.GetString("TOCPanelTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username:.
        /// </summary>
        public static string UsernameLabelText {
            get {
                return ResourceManager.GetString("UsernameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web Maps.
        /// </summary>
        public static string WebMapsLabelText {
            get {
                return ResourceManager.GetString("WebMapsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yards.
        /// </summary>
        public static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
    }
}
